version: "3.8"

services:
  event_generator:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_REGION=ca-central-1
      - AWS_SECRET_ACCESS_KEY=dummy
      - ENVIRONMENT_TYPE=development
      - ENVIRONMENT=local
    ports:
      - 5700:8080
