version: "3.8"

services:
  hello_world:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_REGION=ca-central-1
      - AWS_SECRET_ACCESS_KEY=dummy
      - ENVIRONMENT_TYPE=development
      - ENVIRONMENT=local
      - S3_BUCKET=lendesk-hello-world-local
      - S3_ENDPOINT=http://localstack:4566
    ports:
      - 5700:8080

  localstack:
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=ca-central-1
    image: localstack/localstack:0.12.12
    ports:
      - 4566:4566
    volumes:
      - localstack-data:/tmp/localstack/data
      - ./localstack-entrypoint-initaws.d:/docker-entrypoint-initaws.d

volumes:
  localstack-data:
